import Head from "next/head";
import {
  PaleText,
  PurpleText,
  WhiteText,
} from "@/styled-components/StyledTexts";
import styled from "styled-components";
import StyledFolders from "@/styled-components/StyledFolders";
import { useState } from "react";
import Image from "next/image";
import data from "../../data.json";
import ProjectCard from "@/components/ProjectCard";

export default function projects() {
  const [isProjects, setIsProjects] = useState(true);

  return (
    <>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <StyledProjects>
        <WhiteText className="heading">_projects</WhiteText>

        <StyledFolders>
          <div
            onClick={() => {
              setIsProjects(!isProjects);
            }}
            className={isProjects ? "folder active" : "folder"}
          >
            <Image
              width={8.5}
              height={6}
              className="arrow"
              src={"/assets/triangle.png"}
              alt="triangle"
            />
            <WhiteText>projects</WhiteText>
          </div>
          <div
            className={isProjects ? "files active2" : "files active2-reverse"}
          >
            <div className="wrapper">
              {data.techStacks.map((item) => (
                <div>
                  <input type="checkbox" id={item} />
                  <label htmlFor={item}>{item}</label>
                </div>
              ))}
            </div>
          </div>
        </StyledFolders>
        <div className="main-content">
          {data.projects.map((item) => (
            <>
              <div className="heading">
                <PurpleText>Project {item.id}</PurpleText>{" "}
                <PaleText>/ {item.name}</PaleText>
              </div>

              <ProjectCard data={item} />
            </>
          ))}
        </div>
      </StyledProjects>
    </>
  );
}

const StyledProjects = styled.main`
  .heading {
    margin: 20px;
  }

  .files {
    .wrapper {
      flex-direction: column;
      align-items: start;
      gap: 15px;
      margin-top: 10px;
      div {
        padding: 0;
        gap: 20px;

        input[type="checkbox"] {
          position: absolute;
          opacity: 0;
          width: 18px;
          height: 18px;
        }

        input[type="checkbox"] + label::before {
          content: "";
          display: inline-block;
          width: 16px;
          height: 16px;
          border: 1px solid #607b96;
          background-color: transparent;
          border-radius: 3px;
          margin-right: 15px;
          vertical-align: middle;
        }

        input[type="checkbox"]:checked + label::before {
          background-image: url("./assets/checked.png");
          background-repeat: no-repeat;
          background-position: center;
          background-color: #607b96;
        }
        label {
          font-weight: 200;
          font-size: 16px;
          color: white;
        }
      }
    }
  }

  .main-content {
    display: flex;
    flex-direction: column;
    align-items: center;
    margin-top: 30px;

    .heading {
      margin-bottom: 16px;
      p {
        display: inline;
      }
    }
  }
`;
