import { PaleText, WhiteText } from "@/styled-components/StyledTexts";
import Head from "next/head";
import styled from "styled-components";
import Image from "next/image";
import StyledFolders from "@/styled-components/StyledFolders";
import { useState } from "react";

export default function about() {
  const [isInfo, setisInfo] = useState(true);
  const [isContacts, setIsContacts] = useState(false);
  const [isPersonal, setisPersonal] = useState(true);
  const [isProffesional, setisProffesional] = useState(false);
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <StyledAbout>
        <WhiteText className="heading">_about-me</WhiteText>
        <StyledFolders>
          <div
            onClick={() => {
              setisInfo(!isInfo);
            }}
            className={isInfo ? "folder active" : "folder"}
          >
            <Image
              width={8.5}
              height={6}
              className="arrow"
              src={"/assets/triangle.png"}
              alt="triangle"
            />
            <WhiteText>info</WhiteText>
          </div>
          <div className={isInfo ? "files active2" : "files active2-reverse"}>
            <div
              onClick={() => {
                setisPersonal(!isPersonal);
                setisProffesional(false);
              }}
              className={isPersonal ? "active" : ""}
            >
              {" "}
              <Image
                width={12.73}
                height={7.78}
                className="arrow"
                src={"/assets/arrow.png"}
                alt="arrow"
              />
              <Image
                width={12.73}
                height={7.78}
                src={"/assets/orange-folder.png"}
                alt="arrow"
              />
              <WhiteText>personal</WhiteText>
            </div>
            <div
              onClick={() => {
                setisProffesional(!isProffesional);
                setisPersonal(false);
              }}
              className={isProffesional ? "active" : ""}
            >
              {" "}
              <Image
                width={12.73}
                height={7.78}
                className="arrow"
                src={"/assets/arrow.png"}
                alt="arrow"
              />
              <Image
                width={12.73}
                height={7.78}
                src={"/assets/green-folder.png"}
                alt="arrow"
              />
              <WhiteText>proffesional</WhiteText>
            </div>
          </div>

          <div
            onClick={() => {
              setIsContacts(!isContacts);
            }}
            className={isContacts ? "folder active" : "folder"}
          >
            <Image
              width={8.5}
              height={6}
              className="arrow"
              src={"/assets/triangle.png"}
              alt="triangle"
            />
            <WhiteText>contacts</WhiteText>
          </div>
          <div
            className={isContacts ? "files active2" : "files active2-reverse"}
          >
            <div>
              <Image
                width={12.73}
                height={7.78}
                src={"/assets/mail-icon.png"}
                alt="arrow"
              />
              <PaleText>beqamaisuradze912@gmail.com</PaleText>
            </div>
            <div>
              {" "}
              <Image
                width={12.73}
                height={7.78}
                src={"/assets/phone-icon.png"}
                alt="arrow"
              />
              <PaleText>+(995) 579 09 55 87</PaleText>
            </div>
          </div>
        </StyledFolders>
        <div className="main-content">
          <div className={isPersonal ? "active" : "inactive"}>
            <WhiteText>// info </WhiteText>{" "}
            <PaleText>
              / personal <br /> <br />
            </PaleText>
            <PaleText>
              I have 5 years of experience in web development lorem ipsum dolor
              sit amet, consectetur adipiscing elit, sed do eiusmod tempor
              incididunt ut labore et dolore magna aliqua. Ut enim ad minim
              veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
              ex ea commodo consequat. Duis aute irure dolor in reprehenderit
              in. Duis aute irure dolor in reprehenderit in voluptate velit esse
              cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
              officia deserunt mollit anim id est laborum.
            </PaleText>
          </div>

          <div className={isProffesional ? "active" : "inactive"}>
            <WhiteText>// info </WhiteText>{" "}
            <PaleText>
              / proffesional <br /> <br />
            </PaleText>
            <PaleText>
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's standard dummy text
              ever since the 1500s, when an unknown printer took a galley of
              type and scrambled it to make a type specimen book. It has
              survived not only five centuries, but also the leap into
              electronic typesetting, remaining essentially unchanged. It was
              popularised in the 1960s with the release of Letraset sheets
              containing Lorem Ipsum passages, and more recently with desktop
              publishing software like Aldus PageMaker including versions of
              Lorem Ipsum.
            </PaleText>
          </div>
        </div>
      </StyledAbout>
    </>
  );
}

const StyledAbout = styled.main`
  .heading {
    margin: 20px;
  }

  .main-content {
    position: relative;

    div {
      position: absolute;
      transition: 0.5s;
      padding: 15px;
    }
    .active {
      opacity: 1;
    }

    .inactive {
      opacity: 0;
    }

    p {
      display: inline;
    }
  }
`;
